"""Rotavirus vaccine metaregression project input and output paths"""
ROOT_DIR = FILEPATH
CURR_VSN_DIR = ROOT_DIR + FILEPATH

GDP_DF = ROOT_DIR + FILEPATH
WB_INC_GRPS = ROOT_DIR + FILEPATH
GAVI_ELIG_DF = ROOT_DIR + FILEPATH

RAW_DF_WITHOUT_SENS = ROOT_DIR + FILEPATH
SENS_ANLYS_DF = ROOT_DIR + FILEPATH

UNCONV_CURRENCY_DF = CURR_VSN_DIR + FILEPATH
CONV_CURRENCY_DF = CURR_VSN_DIR + FILEPATH
CLEANED_REG_DF_WITH_SENS = CURR_VSN_DIR + FILEPATH
PAIRED_CWALK_DF = CURR_VSN_DIR + FILEPATH

CWALK_PARAM_SUMMARY = CURR_VSN_DIR + FILEPATH
CWALK_PARAM_DRAWS = CURR_VSN_DIR + FILEPATH

SIGNAL_MR_PKL = CURR_VSN_DIR + FILEPATH
SEL_COVS_PKL = CURR_VSN_DIR + FILEPATH
CV_RESULTS = CURR_VSN_DIR + FILEPATH

CONV_PRED_VACC_COSTS = CURR_VSN_DIR + FILEPATH
PRED_VACC_EFFICACY = ROOT_DIR + FILEPATH

PREDS_DF = CURR_VSN_DIR + FILEPATH
PREDICTIONS = CURR_VSN_DIR + FILEPATH
PREDICTIONS_WITH_ADJUSTMENT = CURR_VSN_DIR + FILEPATH